name: stocksync_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.0.5
  socket_io_client: ^2.0.0
  razorpay_flutter: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#ff0000"
  image: assets/logo.png
  android: true
  ios: false
  fullscreen: true

